name: Build and Test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Deploy if successful
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
         # Trigger the "Deploy" workflow in the same directory
         pwd
         gh workflow run Aish19999/Reusable_workflow/.github/workflows/deploy.yml        
